### ISSUE TITLE
Is p just to control the pretraining blur?

### ISSUE THREAD

**Issue by micimize** [recasens/Saliency-Sampler#4]
As far as I can tell this could all be
```python
 add_pretraining_blur = epoch <= N_pretraining
...
 output,image_output,hm = model(input_var,add_pretraining_blur) 
...
 if add_pretraining_blur: 
```
> We found helpful to blur the resampled input image of the task
network for some epochs at the beginning of the training procedure. It forces
the saliency sampler to zoom deeper into the image in order to further magnify
small details otherwise destroyed by the consequent blur. This is beneficial even
for the final performance of the model with the blur removed.

https://github.com/recasens/Saliency-Sampler/blob/0557addd00c9592f3f6c1be6e37583e9132e4eba/main.py#L193-L196
https://github.com/recasens/Saliency-Sampler/blob/0557addd00c9592f3f6c1be6e37583e9132e4eba/main.py#L199
https://github.com/recasens/Saliency-Sampler/blob/0557addd00c9592f3f6c1be6e37583e9132e4eba/saliency_sampler.py#L117-L120

**Comment by recasens** [comment]
Hi! 

Yes, p was added as to provide more flexibility to the code, but at the end was just used as a binary flag to control the pretraining blur. 

Sorry for the confusion!

**Comment by micimize** [comment]
Thanks!
