### ISSUE TITLE
Help understanding create_grid

### ISSUE THREAD

**Issue by micimize** [recasens/Saliency-Sampler#5]
Hi again – I've been trying to grok the math behind `create_grid`, and am fairly confused. I've fiddled around with `padding_size`, `grid_size`, the `kernel_size` formula, and `fwhm`, and various but nothing seems to result in deterministic warping.

I'm doing some simple  tests on 128x128 transformed mnist data, where I'm attempting to utilize the saliency map of a pretrained network. Below are the input, warped output, and then saliency map:
![image](https://user-images.githubusercontent.com/8343799/86862865-adfb3800-c08f-11ea-99ba-fd4b363b3a0f.png)

which I can get to warp with specific seeds after 10 or so iterations:

<img src="https://user-images.githubusercontent.com/8343799/86864117-34187e00-c092-11ea-9234-8bb77b9a50a9.png" width="600"/>

Essentially, my goal is to isolate some function with the signature:  
`warp_sample(hires_source, lowres_heatmap, warp_factor) -> lowres_warped`
That spreads around resolution to the most salient regions. I understand that was also one of the paper's goals

Anyhow – any advice or comments on how to interpret the math would be greatly appreciated

**Comment by micimize** [comment]
I figured it out purely through lots of troubleshooting! The trick was increasing relative "force" via `lambda x: x ** 4` 
![image](https://user-images.githubusercontent.com/8343799/87112968-d7a09480-c232-11ea-871f-6f1ff7a28f9c.png)

**Comment by xyl-507** [comment]
@micimize 
Sorry to bother! 
Can you give me some advice on visualizing the grid?
Thanks in advance!
![image](https://user-images.githubusercontent.com/69385203/229286824-c3486d76-cd7a-4b9f-8dcf-042c46db2264.png)
